version: "3.8"
services:
  instance1:
    build: ../question1
    networks: [labnet]

  instance2:
    build: ../question1
    networks: [labnet]
  
  dateservice:
    build: ../question5
    ports:
      - "5000:5000"
    networks: [labnet]

  lb:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    depends_on: [instance1, instance2]
    networks: [labnet]

  benchmarker:
    build: ../benchmark
    depends_on: [lb]
    networks: [labnet]
    entrypoint: ["ab", "-n", "1000", "-c", "50", "http://lb/"]

networks:
  labnet:
